"""Adding the Relationship between user and books table

Revision ID: aa2ca07c9f64
Revises: e2cad5a050a6
Create Date: 2025-07-28 15:28:54.477207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa2ca07c9f64'
down_revision: Union[str, Sequence[str], None] = 'e2cad5a050a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'books', ['uid'])
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
