"""Adding the role column to the user table

Revision ID: e2cad5a050a6
Revises: c9b60d1ffd84
Create Date: 2025-07-26 17:35:47.902397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2cad5a050a6'
down_revision: Union[str, Sequence[str], None] = 'c9b60d1ffd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_enum = postgresql.ENUM('USER', 'ADMIN', name='RoleEnum')
    role_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', role_enum , server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    role_enum = postgresql.ENUM('USER', 'ADMIN', name='RoleEnum')
    role_enum.drop(op.get_bind())  # ← Drop the ENUM type from PostgreSQL
    # ### end Alembic commands ###
